/*
 * DIO_cnfg.c
 *
 * Created: 9/13/2019 10:49:52 AM
 *  Author: Peter
 */ 
#include "DIO_cnfg.h"

DIO_cnfg_t DIO_cnfg_arr [NUM_OF_PINS] =
{
	{PORT_C,PIN2,INPUT,NA,PULLUP,INITIALIZED},
	{PORT_C,PIN3,INPUT,NA,PULLUP,INITIALIZED},
	{PORT_C,PIN4,INPUT,NA,PULLUP,INITIALIZED},
	{PORT_C,PIN5,OUTPUT,HIGH,NA,INITIALIZED},
	{PORT_C,PIN6,OUTPUT,HIGH,NA,INITIALIZED},
	{PORT_C,PIN7,OUTPUT,HIGH,NA,INITIALIZED},
	{PORT_B,PIN4,OUTPUT,LOW,NA,INITIALIZED}
};